### ISSUE TITLE
ImportError: No module named path

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [liutairan/eMolFrag#1]
I downloaded your software and run it, but the import error has occurred.

```py
Traceback (most recent call last):
  File "eMolFrag.py", line 63, in <module>
    import path
ImportError: No module named path
```

It seems my python (v2.7.12) environment does not have path module. 
I downloaded path.py from https://github.com/jaraco/path.py and put it in same dir as eMolFrag.py, then it worked well. 
I think it is also a required package, so could you mention it in README and so forth?

**Comment by liutairan** [comment]
Sure, thanks for posting this.

**Comment by liutairan** [comment]
I think you can remove that "import path" would be fine. I updated this bug several months ago, but forgot to post on GitHub. Sorry for the inconvenience. Already updated.

**Comment by keisuke-yanagisawa** [comment]
Thank you for your reply. I confirmed it worked well without ``import path``.
