### ISSUE TITLE
How to use eMolFrag without eSynth?

### ISSUE THREAD

**Issue by Sun694** [liutairan/eMolFrag#4]
Hello,

I would like to use eMolFrag to generate molecule fragments, and then "manually" (probabilistically) generate new molecules (e.g.: randomly sample a set of linkers and bricks, then combine this to create a molecules).

I would like to avoid eSynth as it seems hugely overkill, I at most will be generated 500 molecules at a time.

I could not find any RDKIT or oBabel functionality for this.

What would be the best way to proceed?

Thanks,

Sun

**Comment by liutairan** [comment]
This is a good question. I am not aware of any software can do this job. I can talk to my collaborators about this problem. What is your requirement for the 500 molecules?

**Comment by Sun694** [comment]
> This is a good question. I am not aware of any software can do this job. I can talk to my collaborators about this problem. What is your requirement for the 500 molecules?

I would like to have a function that takes in a set of bricks and linkers, and returns generated molecules.

Ideally, I would like to be able to randomly sample N bricks and linkers, generate some small amount of molecules (20ish), then randomly sample again and repeat until I generate my desired 500.

I realize that in this context, only generating 20 from a given set of bricks/linkers is extremely small. Is there any way to make these 20 "good"? e.g.: only generate ones with high QED, or similar?

Thanks a huge amount in advance,

Sun

**Comment by liutairan** [comment]
> > This is a good question. I am not aware of any software can do this job. I can talk to my collaborators about this problem. What is your requirement for the 500 molecules?
> 
> I would like to have a function that takes in a set of bricks and linkers, and returns generated molecules.
> 
> Ideally, I would like to be able to randomly sample N bricks and linkers, generate some small amount of molecules (20ish), then randomly sample again and repeat until I generate my desired 500.
> 
> I realize that in this context, only generating 20 from a given set of bricks/linkers is extremely small. Is there any way to make these 20 "good"? e.g.: only generate ones with high QED, or similar?
> 
> Thanks a huge amount in advance,
> 
> Sun

I believe this is not a minor revision. Since I am not working on this project anymore, I suggest you to contact Prof. Brylinski at Louisiana State University. You can find his contact information at [Computational Systems Biology Group](http://www.brylinski.org/user/1).

**Comment by Sun694** [comment]
> > > This is a good question. I am not aware of any software can do this job. I can talk to my collaborators about this problem. What is your requirement for the 500 molecules?
> > 
> > 
> > I would like to have a function that takes in a set of bricks and linkers, and returns generated molecules.
> > Ideally, I would like to be able to randomly sample N bricks and linkers, generate some small amount of molecules (20ish), then randomly sample again and repeat until I generate my desired 500.
> > I realize that in this context, only generating 20 from a given set of bricks/linkers is extremely small. Is there any way to make these 20 "good"? e.g.: only generate ones with high QED, or similar?
> > Thanks a huge amount in advance,
> > Sun
> 
> I believe this is not a minor revision. Since I am not working on this project anymore, I suggest you to contact Prof. Brylinski at Louisiana State University. You can find his contact information at [Computational Systems Biology Group](http://www.brylinski.org/user/1).

An email has been sent. Thanks.

**Comment by Sun694** [comment]
For future people:

eMolFrag thankfully provides alot of information on output, and it was not very difficult to build my own tool for. I used the networkx graph library for molecule sketching, then used RDKIT to finalize the graph into a molecule when I was done.

Just in case this might help anyone :)
