### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ponte-vecchio** [liutairan/eMolFrag#5]
# I have two issues:

1. Setting path to pkcombu in `ConfigurePath.py` never works.

- In the step 2 of step 5 in the example given in `README.md`, it says:

> Step 2: Assume path to pkcombu is /.../pkcombu, then type: /.../pkcombu at this step.

Doing so results in `Configure path error`, as is the case for the following examples:
```
/.../eMolFrag/src/
/.../eMolFrag/src/pkcombu
/.../eMolFrag/src/pkcombu/
/.../eMolFrag/src/pkcombu.c
```
The only time it *does* return `Path Correctly Configured` is when `/.../eMolFrag/src/pkcombu.o` is entered.

2) Given all dependencies have been installed and the `PathConfigure.log` has been correctly set, running the given `test-set100` results in no bricks/linkers along with three distinct errors shown below:
```
>>> python eMolFrag.py -i test-set100/ -o test-set100-out -p 16
/home/gandenpa/Documents/python/ML/eMolFrag/test-set100/ /home/gandenpa/Documents/python/ML/eMolFrag/test-set100-out/ 16 0 0 1.0
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Good False
Error Code: 1092. ChopwithRDKit error
Error Code: 1100
something wrong with reading BrickListAll.txt
Error Code: 1110. Read LinkerListAll.txt failed. This may be caused from no linker generated for some reason.
```

I have not modified anything, and simply followed the `README` documentation. Where is this issue arising from?

**Comment by venkateshkolli** [comment]
I have an error with second step of ConfigurePath.py. It is showing {Configure path error, type again:} no matter what I did.
Can someone please guide me with this issue.

**Comment by ponte-vecchio** [comment]
> 
> 
> I have an error with second step of ConfigurePath.py. It is showing {Configure path error, type again:} no matter what I did.
> Can someone please guide me with this issue.

Compile pkcombu then enter `/.../src/pkcombu.o` in step 2 of `configurepath.py`.

**Comment by liutairan** [comment]
Hi, sorry to everyone in this issue. I was busy with postdoc application and moving to another state recently. I will be back to solve these problems as soon as I can. Sorry about this.

**Comment by cplateVT** [comment]
> # I have two issues:
> 1. Setting path to pkcombu in `ConfigurePath.py` never works.
> 
> * In the step 2 of step 5 in the example given in `README.md`, it says:
> 
> > Step 2: Assume path to pkcombu is /.../pkcombu, then type: /.../pkcombu at this step.
> 
> Doing so results in `Configure path error`, as is the case for the following examples:
> 
> ```
> /.../eMolFrag/src/
> /.../eMolFrag/src/pkcombu
> /.../eMolFrag/src/pkcombu/
> /.../eMolFrag/src/pkcombu.c
> ```
> 
> The only time it _does_ return `Path Correctly Configured` is when `/.../eMolFrag/src/pkcombu.o` is entered.
> 
> 2. Given all dependencies have been installed and the `PathConfigure.log` has been correctly set, running the given `test-set100` results in no bricks/linkers along with three distinct errors shown below:
> 
> ```
> >>> python eMolFrag.py -i test-set100/ -o test-set100-out -p 16
> /home/gandenpa/Documents/python/ML/eMolFrag/test-set100/ /home/gandenpa/Documents/python/ML/eMolFrag/test-set100-out/ 16 0 0 1.0
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Good False
> Error Code: 1092. ChopwithRDKit error
> Error Code: 1100
> something wrong with reading BrickListAll.txt
> Error Code: 1110. Read LinkerListAll.txt failed. This may be caused from no linker generated for some reason.
> ```
> 
> I have not modified anything, and simply followed the `README` documentation. Where is this issue arising from?

I didn't encounter an issue with the configurepath.py at all, but running the test set, I faced the same errors. Is it possible that this has something to do with having newer versions of rdkit? I'm assuming that you all installed rdkit2019. I tried installing the rdkit specified in the README but either my system or python version is incompatible with the environment and it couldn't install

**Comment by ponte-vecchio** [comment]
Lack of response; Closing.
